#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_PLAYER 10
#define MAX_PARTIES 5
#define MAX_NAME_SIZE 50
#define MAX_COMMAND_SIZE 50
#define MAX_DESTINATAIRE_SIZE 50
#define MAX_BODY_SIZE 2000
#define MAX_MESSAGE_SIZE 2150

#define FACTEUR_DAJUSTEMENT_ELO 32
#endif // CONSTANTS_H